### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by tringler** [goodfield/python-maxcube-api#3]
Hello @goodfield ,

can you tell me how to implement your api into configuration.yaml of Home Assistant?

I found that thread [eq3-max-i2c-one-wire](https://community.home-assistant.io/t/eq3-max-i2c-one-wire/118/5) in the Home Assistant forum, but component thermostat.max is not existing anymore (component climate.max is also not existing)

Do you have any hint for me how to get it working? Thanks in Advance, Thomas

**Comment by goodfield** [comment]
Hi
sorry, but i'm not longer using home assistant ... this library was never integrated into home-assistant, that's why you can't use it.

You would have to write a plugin for home assistant (https://home-assistant.io/developers/), for the communication you could use this api.

Best regards,

David
